import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { Providers } from "./providers";
import Animate from "./Animate";
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head>
          <meta name="viewport" content="width=device-width,initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </head>
        <body className={`${montserrat.variable} dark:bg-[#1A1A1B]`}>
          <Providers>
            <Nav />
            <div className="px-[6vw] overflow-x-hidden ">{children}</div>
            <Footer />
          </Providers>
        </body>
      </html>
    </>
  );
}
